name: Client Deploy

on:
  push:
    branches:
    - main
    paths:
    - 'website-client/**'
    - '.github/workflows/client-**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Change to ubuntu-20.04 when it is fully supported.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Build & Push
        run: |
          pushd website-client
          docker build -t juharris/switch-remoteplay-client:latest .
          docker run --rm -e CI=true --name switch-remoteplay-client juharris/switch-remoteplay-client:latest yarn test
          docker run --rm -e CI=true --name switch-remoteplay-client juharris/switch-remoteplay-client:latest yarn lint
          docker login --username juharris --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push juharris/switch-remoteplay-client:latest
